### PR TITLE
Add limit of parts in BOM rows

### PR DESCRIPTION
**Pull request by mengstr**
The number of components that are merged into the same row in the BOM file is limited. If there are too many you'll get an "Internal Server Error" when JLCPCB is processing it. 

Their support told me 20 parts per row is the limit but I've tested with 50 and it works, so I split the difference and set it to 30 here. I guess the 20 was only a suggestion :)

### CODE REVIEW

**Comment by bennymeg** [comment]
Thanks,
Could you please define `bomRowLimit = 30` it the config file and us it instead of hardcoding this number?

**Comment by mengstr** [comment]
Sure, will do. That sounds like a good improvement..

**Comment by mengstr** [comment]
I was lazy and changed the files directly in the GitHub editor, so you might want to do a squash while merging. 

But what is the correct workflow for developing a KiCad plugin? Should I have cloned it into my Kicad-plugin folder and worked from there to be able to easily test the changes?

**Comment by bennymeg** [comment]
What I usually do is:
1. test the core feature using the built-in python api
2. modify the loaded plugin in the kicad plugin directory, whilst reloading the plugin after each change
3. update the and test the updated plugin

**Review by bennymeg — APPROVED** [review]

**Comment by revk** [comment]
Wow, just ran in to this, and was just about to do a pull request when I saw it was already done, cool.

**Comment by revk** [comment]
My tests suggest JLC are fine with as many as 400 designators per row.

**Comment by mengstr** [comment]
The board that I had problem with had 512 of the same part on it. And the support told me max 20, so if it works with like 400 maybe we should up the current set default value of 30 up to, say.... 128 or 256.  

If the LCSC part number is already in the KiCad it really doesn't matter, but if doing it by hand after uploading the BOM to JLC then it gets annoying to have to part-search-and-update many words there. So a slightly higher number might be better.

**Comment by revk** [comment]
> The board that I had problem with had 512 of the same part on it. And the support told me max 20, so if it works with like 400 maybe we should up the current set default value of 30 up to, say.... 128 or 256.

LOL, they told me 200, I tested and 400 work (498 does not).

**Comment by romain145** [comment]
I just tested with 256 and it did not work.
The support told me that the limit is 200, and indeed after changing to 200 it now works.

**Pull request merged**
