### PR TITLE
Rotation offset field

### PR DESCRIPTION
**Pull request by antonxy**
Hi, thank you for your plugin. It was really useful today as my own export script broke with the update to KiCad 6.
I had the same issue as #20 and decided to implement a rotation offset field so that I can save the rotation offsets and don't have to rotate manually on the JLC webpage each time.
Since the value in the rotation field might be incorrectly formatted (not a number) I also added displaying of errors in a message box.

### CODE REVIEW

**Comment by zapta** [comment]
That's great. Thanks @antonxy.  Any chance you can also add JLC offsets for x and y?

**Comment by antonxy** [comment]
Hmm, yes that could be useful also. But where would you get the exact xy offset from? For rotation it's quite easy to see in JLCs order preview that your component is 90 degrees off for example. But how do you know your component is shifted by 1.2mm?

**Comment by bennymeg** [comment]
In my experience, only THT components appear shifted. It is more likely a bug in JLC 3D viewer.

**Comment by zapta** [comment]
In the JLCPCB component page I select PCB Footprint or Symbol , then I
click Free Trial, and land on the EasyEda page in the link below. Then I
drag the footprint and it shows the red cross hair that indicates the
expected center.  If anybody knows of an easier way please post here.


https://i.imgur.com/CEVxGMe.png

**Pull request merged**
